export const CHANGE_USERS = 'CHANGE_USERS';
export const SORT_USERS = 'SORT_USERS';
export const FILTER_BY_COLUMN = 'FILTER_BY_COLUMN';
export const FILTER_BY_ARRAY = 'FILTER_BY_ARRAY';
export const SWITCH_TOOGLE = 'SWITCH_TOOGLE';
export const MULTISELECT_FILTER = 'MULTISELECT_FILTER';
export const PRESS_KEYS_CONTROLL = 'PRESS_KEYS_CONTROLL';